version: 2.1

build_template: &build_template
  environment:
    TERM: dumb
  machine: true
  working_directory: ~/repo
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "build.gradle.kts" }}
          - v1-dependencies-
    - run: ./gradlew compileTestKotlin
    - save_cache:
        paths:
          - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle.kts" }}
    - run:
        command: ./gradlew build
        no_output_timeout: 20m
    - store_artifacts:
        path: ./build/reports/tests
        destination: test-reports
    - store_artifacts:
        path: ./build/diagnoses
        destination: diagnoses
    - store_test_results:
        path: ./build/test-results
jobs:
  build1:
    <<: *build_template
  build2:
    <<: *build_template
  build3:
    <<: *build_template
  build4:
    <<: *build_template
  release:
    docker:
      - image: circleci/openjdk:8u181-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - run: ./gradlew release
      - run: ./gradlew publish
workflows:
  version: 2
  release_workflow:
    jobs:
      - build1
      - build2
      - build3
      - build4
      - approve_release:
          type: approval
          requires:
            - build1
          filters:
            branches:
              only: master
            tags:
              only: /release-*-alpha/
      - release:
          requires:
            - approve_release
