name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      release:
        description: 'Release? yes/no'
        default: 'no'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run: [1, 2, 3, 4] # run a few times to detect flakiness
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
        timeout-minutes: 20
  build-check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "All build jobs successful."
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    needs: build-check
    if: github.event.inputs.release == 'yes'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Auth Maven
        id: publish-token
        uses: atlassian-labs/artifact-publish-token@v1.0.1
      - name: Release
        env:
          atlassian_private_username: ${{ steps.publish-token.outputs.artifactoryUsername }}
          atlassian_private_password: ${{ steps.publish-token.outputs.artifactoryApiKey }}
        run: |
          ./gradlew release \
              -Prelease.customUsername=${{ github.actor }} \
              -Prelease.customPassword=${{ github.token }}
          ./gradlew publish
